### PR TITLE
Refactored client-side logic. Made resume form stateful.

### PR DESCRIPTION
**Pull request by jarrmill**
This pull request refactors our main ApplicantForm file, changing it from 391 lines of code to 67 lines. To do this, each section (Education, Work Experience, etc) was put into its own file and the form itself was made stateful. Because of this, we can remove the long function that interacts/transforms the form data on submit.

Lastly, to make the form stateful, a new file, `helperFunctions.js`, was created. This file has a `getResumeData` and `setResumeData`. It can later be extended to have `removeResumeData` when we want to have a 'remove section' button.

### CODE REVIEW

**Comment by Chadcramer** [comment]
Jarrod this is a hell of a pull request. It looks awesome on my end, and nothing jumps out to be wrong.

**Comment by jarrmill** [comment]
Chad, yeah it is a biggie all right. In the future I'd like to avoid such big changes, but was a little unsure on how to do it here considering it is just refactoring code, and it all came together only at the end. I'll work on making them smaller though, thanks for reviewing it :-)

**Comment by jarrmill** [comment]
It is also worth noting that the majority of the new files are not my code, or even new code, but code from @NicholasMiron that I refactored from the main applicationform.js file into its own little file.

**Comment by jarrmill** [comment]
I think my changes might be easier to digest with some pictures. After all, 75% of these changes are just reorganizing and refactoring files.

**Here is the master branch of HireUs. Note that the meat of the app is in applicantForm.js, which contains each section (Education, Work Experience, etc)** 
MasterHireUS

**Here is the rough outline of proposed changes. Note that the Applicant side is now in its own folder, with two new subfolders, Inputs and Sections**

HireUs-General

**Lastly, here is the expanded subfolders. These should be pretty self explanatory, and significantly cut down the code in ApplicantForm.js**

ResumeForm Expanded

I know the pull request is big, but it is that way in large part because files were moved and renamed. The biggest logic addition that was added was _helperFunctions.js_, which is basically a big switch statement to intelligently insert values into the nested object.

I hope this helps! Please let me know if there are any questions.

**Pull request merged**
